baseURL: https://bengreenwald.io/
languageCode: en-us
defaultContentLanguage: en
title: Ben Greenwald
theme: recluse
rssLimit: 10
copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License.
enableEmoji: yes
author:
  name: Ben Greenwald
blackfriday: {}
taxonomies:
  tag: tags
params:
  code_copy_button: yes
  dateform: Jan 2, 2006
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04 -0700
  dateformShort: Jan 2
  # footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/"
  #   target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  homeSubtitle: Data & Product Analytics
  justifyContent: no
  relatedPosts: no
  social:
    - name: email
      url: mailto:greenwab11@gmail.com
    - name: github
      url: https://github.com/bengreenwald
    - name: linkedin
      url: https://www.linkedin.com/in/bengreenwald/
  themeColor: '#494f5c'
menu:
  main:
    - name: Posts
      url: post/
      weight: 20
    - name: About
      url: about/
      weight: 10
